export const ActionTypes = {
  SET_HALLS: "SET_HALLS",
  GET_HALLS: "GET_HALLS",
  BOOK_HALL: "BOOK_HALL",
  GET_BOOKINGS: "GET_BOOKINGS",
  CANCEL_BOOKING: "CANCEL_BOOKING",
  VALIDATE_BOOKING: "VALIDATE_BOOKING",
  GET_VALIDATED_BOOKINGS: "GET_VALIDATED_BOOKINGS",
  GET_CANCELLED_BOOKINGS: "GET_CANCELLED_BOOKINGS",
};
